volumes:
  findex-data:
    external: true

  pg-admin:
    external: true

services:
  fastapi:
    env_file:
      - .env
    environment:
      WAIT_HOSTS: postgres:5432
      CORS_HOST: http://localhost:3000
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://user:secret@postgres/findexdb

    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - findex-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: findexdb
    ports:
      - 15432:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email911.com
      PGADMIN_DEFAULT_PASSWORD: password911
      PGADMIN_DISABLE_POSTFIX: 1
